"""Configuration and constants used by the bot."""

from .env import Settings, get_settings
from .constants import (
    API_ENDPOINTS,
    CONTEXT_LIMIT_OPTIONS,
    DEFAULT_CONTEXT_LIMIT,
    DEFAULT_MODEL,
    DEFAULT_MODEL_MAX_TOKENS,
    DEFAULT_STATS_DISPLAY,
    DEFAULT_SYSTEM_PROMPT,
    DEFAULT_THEME,
    STATS_DISPLAY_OPTIONS,
    MODEL_MAX_TOKENS,
    MODEL_PRICING_PER_1K,
    PROVIDER_LABELS,
    PROVIDER_LIST_ENABLED,
    StatsDisplay,
    THEME_OPTIONS,
)

__all__ = [
    "API_ENDPOINTS",
    "CONTEXT_LIMIT_OPTIONS",
    "DEFAULT_CONTEXT_LIMIT",
    "DEFAULT_MODEL",
    "DEFAULT_MODEL_MAX_TOKENS",
    "DEFAULT_STATS_DISPLAY",
    "DEFAULT_SYSTEM_PROMPT",
    "DEFAULT_THEME",
    "MODEL_MAX_TOKENS",
    "MODEL_PRICING_PER_1K",
    "PROVIDER_LABELS",
    "PROVIDER_LIST_ENABLED",
    "Settings",
    "StatsDisplay",
    "STATS_DISPLAY_OPTIONS",
    "THEME_OPTIONS",
    "get_settings",
]
